### PR TITLE
Update yajl-ruby

### PR DESCRIPTION
**Pull request by rgbkrk**
Solely because I want my github to stop showing this repository's out-of-date-ness in my notifications.

/cc @smashwilson

### CODE REVIEW

**Comment by nimbinatus** [comment]
Looks like pygments needs to be updated, as well. I'll test and review in a bit.

**Comment by rgbkrk** [comment]
Oh hi! Thanks! I submitted the PR just for fun, so it's totally ok if you make a separate PR that does this properly.

**Comment by nimbinatus** [comment]
Lol, no problem. I'll see if this PR can patch the alert for now as we'll be swinging back to do some proper updates in a bit :)

**Comment by nimbinatus** [comment]
Unfortunately, to really patch this requires moving to Jekyll 3+, so this might take a little while to get a proper fix up, and this patch breaks the preparer. I'll mark the vulnerability as acknowledged so you don't continue to see the reminder.

**Comment by rgbkrk** [comment]
Cool! Great to see deconst in good hands. 😄

**Comment by rgbkrk** [comment]
Closing my inactive PRs for now, since I'm definitely not going to come back to fixing this and you've got bigger plans ahead.

**Comment by nimbinatus** [comment]
@rgbkrk still, thank you! You all probably will see a lot of activity in these repos in the next 6-12 months :)

**Pull request closed without merging**
